# Site settings
title: Android 从入门当放弃
email: oaierp@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://jiezzzo.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: 有想法儿总是好的_(:зゝ∠)_

# Social icons
facebook: oaierp
linkedin: 杰-赵-b1b7ba125
github: jiezzzo
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM   
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

pygments: true