# Site settings
title: 凉水是个好名字
email: oaierp@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://jiezzzo.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: 当一个戏精遇到另外一个戏精_(:зゝ∠)_

# Social icons
linkedin: 杰-赵-b1b7ba125
github: jiezzzo
deviantart: username
codepen: username

highlighter: rouge
pygments: true

footer: © Taken theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM   
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil